//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("projectgen")]
[assembly: AssemblyProduct("projectgen")]
[assembly: AssemblyDescription("description of projectgen.")]
[assembly: AssemblyCompany("Rik Cousens")]
[assembly: AssemblyCopyright("Copyright © 2017-2018, Rik Cousens")]
#if DEBUG
[assembly: AssemblyConfiguration("Debug version")]
#else
[assembly:AssemblyConfiguration("Release version")]
#endif
[assembly: ComVisible(false)]

[assembly: AssemblyVersion("1.0.1.2")]
