//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Diagnostics.CodeAnalysis;
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("projectgen")]
[assembly: AssemblyProduct("projectgen")]
[assembly: AssemblyDescription("description of projectgen.")]
[assembly: AssemblyCompany("Rik Cousens")]
[assembly: AssemblyCopyright("Copyright © 2017-2020, Rik Cousens")]
#if DEBUG
[assembly: AssemblyConfiguration("Debug version")]
#else
[assembly:AssemblyConfiguration("Release version")]
#endif
[assembly: ComVisible(false)]

[assembly: AssemblyVersion("1.0.2.0")]
// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: SuppressMessage("Style","IDE1006:Naming Styles"	)]