//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DevExpress.Skins;
using DevExpress.UserSkins;
using DevExpress.XtraBars;
using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Windows.Forms;


namespace NSAaa {
    
    public partial class aaaForm {
        public aaaForm() {
            InitializeComponent();
        }
        void showAbout(object sender, ItemClickEventArgs e) {
            Debug.Print("here");
        }
        void exitApp(object sender, ItemClickEventArgs e) {
            CancelEventArgs cea = new CancelEventArgs();

            Application.Exit(cea);
            if (cea.Cancel) {
                return;
            }
            Application.Exit();
        }
        void formLoad(object sender, EventArgs ea) {
        }
        [STAThread()]
        public static void Main(string[] args) {
            BonusSkins.Register();
            SkinManager.EnableFormSkins();
            Application.EnableVisualStyles();
            Application.SetCompatibleTextRenderingDefault(false);
            Application.Run(new aaaForm());
        }
    }
}
